pub mod instrdata;

use super::{SApu, instructions::instructions::Instruction};

impl SApu {
    pub fn execute_instruction(&mut self, instruction: &Instruction) {
        self.execute_op(&instruction);

        self.cycle_time += instruction.get_cycle_time();

        self.pc = self.pc.wrapping_add(instruction.get_length() as u16);
    }


    fn execute_op(&mut self, instruction: &Instruction) {
        let instr_data = self.get_instr_data(instruction);

        match instruction {
            Instruction::MOV(_) => todo!(),
            Instruction::STA(_) => todo!(),
            Instruction::LDA(_) => todo!(),
            Instruction::STX(_) => todo!(),
            Instruction::LDX(_) => todo!(),
            Instruction::STY(_) => todo!(),
            Instruction::LDY(_) => todo!(),
            Instruction::ADC(_) => todo!(),
            Instruction::SBC(_) => todo!(),
            Instruction::CMP(_) => todo!(),
            Instruction::CPX(_) => todo!(),
            Instruction::CPY(_) => todo!(),
            Instruction::AND(_) => todo!(),
            Instruction::OR(_) => todo!(),
            Instruction::EOR(_) => todo!(),
            Instruction::ASL(_) => todo!(),
            Instruction::ASLA(_) => todo!(),
            Instruction::LSR(_) => todo!(),
            Instruction::LSRA(_) => todo!(),
            Instruction::ROL(_) => todo!(),
            Instruction::ROLA(_) => todo!(),
            Instruction::ROR(_) => todo!(),
            Instruction::RORA(_) => todo!(),
            Instruction::XCN => todo!(),
            Instruction::INC(_) => todo!(),
            Instruction::INX => todo!(),
            Instruction::INY => todo!(),
            Instruction::INA => todo!(),
            Instruction::DEC(_) => todo!(),
            Instruction::DEX => todo!(),
            Instruction::DEY => todo!(),
            Instruction::DEA => todo!(),
            Instruction::STW(_) => todo!(),
            Instruction::LDW(_) => todo!(),
            Instruction::INCW(_) => todo!(),
            Instruction::DECW(_) => todo!(),
            Instruction::ADDW(_) => todo!(),
            Instruction::SUBW(_) => todo!(),
            Instruction::CMPW(_) => todo!(),
            Instruction::MUL => todo!(),
            Instruction::DIV => todo!(),
            Instruction::DAA => todo!(),
            Instruction::DAS => todo!(),
            Instruction::BRA(_) => todo!(),
            Instruction::BEQ(_) => todo!(),
            Instruction::BNE(_) => todo!(),
            Instruction::BCS(_) => todo!(),
            Instruction::BCC(_) => todo!(),
            Instruction::BVS(_) => todo!(),
            Instruction::BVC(_) => todo!(),
            Instruction::BMI(_) => todo!(),
            Instruction::BPL(_) => todo!(),
            Instruction::BBS(_, _) => todo!(),
            Instruction::BBC(_, _) => todo!(),
            Instruction::CBNE(_) => todo!(),
            Instruction::DBNZ(_) => todo!(),
            Instruction::JMP(_) => todo!(),
            Instruction::CALL(_) => todo!(),
            Instruction::PCALL(_) => todo!(),
            Instruction::TCALL(_, _) => todo!(),
            Instruction::BRK => todo!(),
            Instruction::RET => todo!(),
            Instruction::RETI => todo!(),
            Instruction::PUSHP => todo!(),
            Instruction::PUSHA => todo!(),
            Instruction::PUSHX => todo!(),
            Instruction::PUSHY => todo!(),
            Instruction::POPP => todo!(),
            Instruction::POPA => todo!(),
            Instruction::POPX => todo!(),
            Instruction::POPY => todo!(),
            Instruction::SET1(_, _) => todo!(),
            Instruction::CLR1(_, _) => todo!(),
            Instruction::TSET1(_) => todo!(),
            Instruction::TCLR1(_) => todo!(),
            Instruction::AND1(_) => todo!(),
            Instruction::OR1(_) => todo!(),
            Instruction::ANDNOT1(_) => todo!(),
            Instruction::ORNOT1(_) => todo!(),
            Instruction::EOR1(_) => todo!(),
            Instruction::NOT1(_) => todo!(),
            Instruction::ST1(_) => todo!(),
            Instruction::LD1(_) => todo!(),
            Instruction::CLRC => todo!(),
            Instruction::SETC => todo!(),
            Instruction::NOTC => todo!(),
            Instruction::CLRV => todo!(),
            Instruction::SETP => todo!(),
            Instruction::CLRP => todo!(),
            Instruction::EI => todo!(),
            Instruction::DI => todo!(),
            Instruction::NOP => todo!(),
            Instruction::SLEEP => todo!(),
            Instruction::STOP => todo!(),
            Instruction::TAX => todo!(),
            Instruction::TXA => todo!(),
            Instruction::TAY => todo!(),
            Instruction::TYA => todo!(),
            Instruction::TSX => todo!(),
            Instruction::TXS => todo!(),
        }
    }
}